import {
  CATEGORY_URL,
  DISCOUNT_URL,
  ORDER_URL,
  REGION_URL,
  SUBJECT_URL,
  TAG_URL,
  TICKET_URL,
} from 'constants/endPoints'
import {
  CategoryIcon,
  DashboardIcon,
  GiftCardsIcon,
  RolesIcon,
  TrackingOrdersIcon,
  UsersIcon,
} from 'ui/components/icons'

export const SidebarList = (t: any): any => {
  return [
    {
      id: 1,
      title: t('role'),
      icon: <RolesIcon className="w-10" />,
      path: '/roles',
      isDisabled: false,
    },
    {
      id: 2,
      title: t('user'),
      icon: <UsersIcon className="w-10" />,
      path: '/users',
      isDisabled: false,
    },
    {
      id: 3,
      title: t('permissions'),
      icon: <UsersIcon className="w-10" />,
      path: '/permissions',
      isDisabled: false,
    },
    {
      id: 4,
      title: t('region'),
      icon: <UsersIcon className="w-10" />,
      path: REGION_URL,
      isDisabled: false,
    },
    {
      id: 5,
      title: t('category'),
      icon: <CategoryIcon className="w-10" />,
      path: CATEGORY_URL,
      isDisabled: false,
    },
    {
      id: 6,
      title: t('giftCardPriceSidbar'),
      icon: <GiftCardsIcon className="w-10" />,
      path: '/giftCardPrice',
      isDisabled: false,
    },

    {
      id: 7,
      title: t('productManagement'),
      icon: <UsersIcon className="w-10" />,
      path: '/product',
      isDisabled: false,
    },
    {
      id: 8,
      title: t('package'),
      icon: <DashboardIcon className="w-10" />,
      path: '/package',
      isDisabled: false,
    },
    {
      id: 9,
      title: t('tokensManagement'),
      icon: <UsersIcon className="w-10" />,
      path: '/tokenManagement',
      isDisabled: false,
    },
    {
      id: 10,
      title: t('inputsManagement'),
      icon: <UsersIcon className="w-10" />,
      path: '/inputManagement',
      isDisabled: false,
    },
    {
      id: 23,
      title: t('formsManagement'),
      icon: <UsersIcon className="w-10" />,
      path: '/formManagement',
      isDisabled: false,
    },
    {
      id: 11,
      title: t('trackingOrders'),
      icon: <TrackingOrdersIcon className="w-10" />,
      path: ORDER_URL,
      isDisabled: false,
    },
    {
      id: 12,
      title: t('ticket'),
      icon: <UsersIcon className="w-10" />,
      path: TICKET_URL,
      isDisabled: false,
    },
    {
      id: 13,
      title: t('subjects'),
      icon: <UsersIcon className="w-10" />,
      path: SUBJECT_URL,
      isDisabled: false,
    },
    {
      id: 14,
      title: t('faq'),
      icon: <UsersIcon className="w-10" />,
      path: '/faq',
      isDisabled: false,
    },
    {
      id: 15,
      title: t('currency'),
      icon: <UsersIcon className="w-10" />,
      path: '/currency',
    },
    {
      id: 16,
      title: t('onlinePayment'),
      icon: <UsersIcon className="w-10" />,
      path: '/onlinePayment',
      isDisabled: false,
    },
    {
      id: 17,
      title: t('tag'),
      icon: <UsersIcon className="w-10" />,
      path: TAG_URL,
      isDisabled: false,
    },
    {
      id: 18,
      title: t('discount'),
      icon: <UsersIcon className="w-10" />,
      path: DISCOUNT_URL,
      isDisabled: false,
    },
    {
      id: 19,
      title: t('notification'),
      icon: <UsersIcon className="w-10" />,
      path: '/notification',
      isDisabled: false,
    },
    {
      id: 20,
      title: t('pageUrl'),
      icon: <UsersIcon className="w-10" />,
      path: '/pageUrl',
      isDisabled: false,
    },
    {
      id: 21,
      title: t('bannerManagement'),
      icon: <UsersIcon className="w-10" />,
      path: '/bannerManagement',
      isDisabled: false,
    },
    {
      id: 22,
      title: t('bannerImageManagement'),
      icon: <UsersIcon className="w-10" />,
      path: '/bannerImage',
      isDisabled: false,
    },
    {
      id: 23,
      title: t('userGroupManagement'),
      icon: <UsersIcon className="w-10" />,
      path: '/userGroupManagement',
      isDisabled: false,
    },
  ]
}
