export const colors = {
  'primary-saturation': 'var(--primary-saturation)',
  'primary-default': 'var(--primary-default)',
  'primary-hover': 'var(--primary-hover)',
  'primary-active': 'var(--primary-active)',
  'primary-disable': 'var(--primary-disable)',
  'primary-background': 'var(--primary-background)',

  'success-default': 'var(--success-default)',
  'success-hover': 'var(--success-hover)',
  'success-active': 'var(--success-active)',

  'tint-100': 'var(--tint-100)',
  'tint-200': 'var(--tint-200)',
  'tint-300': 'var(--tint-300)',
  'tint-400': 'var(--tint-400)',
  'tint-500': 'var(--tint-500)',
  'tint-600': 'var(--tint-600)',
  'tint-700': 'var(--tint-700)',

  'shade-100': 'var(--shade-100)',
  'shade-200': 'var(--shade-200)',
  'shade-300': 'var(--shade-300)',
  'shade-400': 'var(--shade-400)',
  'shade-500': 'var(--shade-500)',
  'shade-600': 'var(--shade-600)',

  'trueGray-100': 'var(--trueGray-100)',
  'trueGray-150': 'var(--trueGray-150)',
  'trueGray-200': 'var(--trueGray-200)',
  'trueGray-250': 'var(--trueGray-250)',
  'trueGray-300': 'var(--trueGray-300)',
  'trueGray-350': 'var(--trueGray-350)',
  'trueGray-400': 'var(--trueGray-400)',
  'trueGray-450': 'var(--trueGray-450)',
  'trueGray-500': 'var(--trueGray-500)',
  'trueGray-550': 'var(--trueGray-550)',
  'trueGray-600': 'var(--trueGray-600)',
  'trueGray-650': 'var(--trueGray-650)',
  'trueGray-700': 'var(--trueGray-700)',
  'trueGray-800': 'var(--trueGray-800)',
  'trueGray-900': 'var(--trueGray-900)',

  'error-default': 'var(--error-default)',
  'error-hover': 'var(--error-hover)',
  'error-active': 'var(--error-active)',
  'error-border': 'var(--error-border)',
  'error-background': 'var(--error-background)',

  'warning-default': 'var(--warning-default)',
  'warning-hover': 'var(--warning-hover)',
  'warning-status': 'var(--warning-status)',
  'warning-active': 'var(--warning-active)',
  'warning-border': 'var(--warning-border)',
  'warning-background': 'var(--warning-background)',

  'orange-default': 'var(--orange-default)',
  'orange-light': 'var(--orange-light)',
  'blue-default': 'var(--blue-default)',

  stroke: 'var(--stroke)',
  darkTypo: 'var(--darkTypo)',
  outlineSecondaryBtn: 'var(--outlineSecondaryBtn)',

  customWhite: 'var(--customWhite)',
  grayWhite: 'var(--grayWhite)',
  test: 'blue',
  danger: 'rgb(var(--color-danger) / <alpha-value>)',
}
